### ISSUE TITLE
State of the repository

### ISSUE THREAD

**Issue by ivajon** [Ben-PH/SimpleFOC-rs#7]
Hi!

I need to work with BLDC Motors on a project. For this, we have made custom esc boards where we drive the phases using PWM signals. I looking to do this with FOC/SVM and came across this project. I was wondering what the state of it is.
Should I expect to be able to get a motor to spin using it and are there any caveats that one would need to consider when using this project for a simple current-controlled ESC?

Given the discussions in #4, I gather that the current control should be considered a work in progress. This is no issue for us though.

If there are any patches needed to make this work that are not massive we could look into fixing those and upstreaming the fixes.

**Comment by Ben-PH** [comment]
Hi, sorry for delayed response. This has been abandonware for a short while, mostly because I don't have the hardware to test. Send me an email, and we can have a detailed chat. Would be happy to see it work for you.
